namespace :test do

  desc "Run the DTModelStorage Tests for iOS"
  task :ios do
    $ios_success = system("xcodebuild test -scheme 'iOS Tests' -destination 'name=iPhone Retina (4-inch),OS=7.0' | xcpretty -tc; test ${PIPESTATUS[0]} -eq 0")
  end

  desc "Run the DTModelStorage Tests for Mac OS X"
  task :osx do
    $osx_success = system("xcodebuild test -scheme 'OS X Tests' | xcpretty -tc; test ${PIPESTATUS[0]} -eq 0")
  end
end

desc "Run the DTModelStorage Tests for iOS & Mac OS X"
task :test => ['test:ios', 'test:osx'] do
  puts "\033[0;31m! iOS unit tests failed" unless $ios_success
  puts "\033[0;31m! OS X unit tests failed" unless $osx_success
  if $ios_success && $osx_success
    puts "\033[0;32m** All tests executed successfully"
  else
    exit(-1)
  end
end

task :default => 'test'
