fastlane_version "1.98.0"

lane :test_ios12 do
  scan(devices: ["iPhone X (12.0)"])
  sh "bash ../codecov.sh"
end

lane :test_ios11 do
  scan(devices: ["iPhone X (11.4)"])
end

lane :test_tvos12 do
  scan(device: "Apple TV")
end

lane :test_tvos11 do
  scan(device: "Apple TV")
end

lane :pod_lint do
  pod_lib_lint(allow_warnings: true, verbose: true)
end

lane :test_ios_swift3 do
  scan(devices: ["iPhone X (12.0)"], xcargs: "SWIFT_VERSION=3.0")
end

lane :test_ios_swift4 do
  scan(devices: ["iPhone X (12.0)"], xcargs: "SWIFT_VERSION=4.0")
end

lane :test_tvos_swift3 do
  scan(devices: ["Apple TV"], xcargs: "SWIFT_VERSION=3.0")
end

lane :test_tvos_swift4 do
  scan(devices: ["Apple TV"], xcargs: "SWIFT_VERSION=4.0")
end

lane :test_xcode9_ios_swift3 do
  scan(device: "iPhone X (11.4)", xcargs: "SWIFT_VERSION=3.0")
end

lane :test_xcode9_ios_swift4 do
  scan(device: "iPhone X (11.4)", xcargs: "SWIFT_VERSION=4.0")
end

lane :carthage_build do
  carthage(command: "build", platform: "iOS,tvOS", no_skip_current: true, verbose: false)
end

lane :release do |params|
  version = params[:version]

  abort "You must specify a version in semver format." if version.nil? || version.scan(/\d+\.\d+\.\d+(-\w+\.\d+)?/).length == 0

  puts "Setting Framework version"
  increment_version_number_in_plist(
      version_number: version,
      target: "DTModelStorage"
  )
  increment_version_number_in_plist(
      version_number: version,
      target: "RealmStorage"
  )

  Dir.chdir("..") do

    puts "Updating podspec."
    filename = "DTModelStorage.podspec"
    contents = File.read(filename)
    contents.gsub!(/s\.version\s*=\s"\d+\.\d+\.\d+(-\w+\.\d)?"/, "s.version      = \"#{version}\"")
    File.open(filename, 'w') { |file| file.puts contents }

    puts "Updating changelog."
    changelog_filename = "CHANGELOG.md"
    changelog = File.read(changelog_filename)
    changelog.gsub!(/# Next/, "# Next\n\n## [#{version}](https://github.com/DenTelezhkin/DTModelStorage/releases/tag/#{version})")
    File.open(changelog_filename, 'w') { |file| file.puts changelog }

    puts "Comitting, tagging, and pushing."
    message = "Releasing version #{version}."
    sh "git commit -am '#{message}'"
    sh "git tag #{version} -m '#{message}'"
    sh "git push --follow-tags"

    puts "Pushing to CocoaPods trunk."
    sh "bundle exec pod trunk push DTModelStorage.podspec --allow-warnings"

    puts "Preparing Carthage binary framework."

    sh "carthage build --no-skip-current --platform iOS,tvOS"
    sh "carthage archive DTModelStorage"

    puts "Pushing as a GitHub Release."
    fastlane_require 'octokit'
    stripped_changelog = changelog.split(/^## /)[1].split("\n")[1..-1].join("\n").strip
    client = Octokit::Client.new(netrc: true)
    client.create_release('DenTelezhkin/DTModelStorage',
                     version,
                     name: version,
                     body: stripped_changelog)

    puts "Attaching Carthage prebuilt binary to release."
    releases = client.releases('DenTelezhkin/DTModelStorage')
    client.upload_asset(releases[0].url, 'DTModelStorage.framework.zip')
  end
end
